import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Database } from "lucide-react";
import * as XLSX from 'xlsx';

export default function BackupPage() {
  const [isExporting, setIsExporting] = useState(false);

  const exportToExcel = async () => {
    setIsExporting(true);
    
    try {
      // Fetch all data
      const [deals, lps, gps, investments, capitalActivities, users] = await Promise.all([
        base44.entities.Deal.list(),
        base44.entities.LimitedPartner.list(),
        base44.entities.GeneralPartner.list(),
        base44.entities.Investment.list(),
        base44.entities.CapitalActivity.list(),
        base44.entities.User.list()
      ]);

      // Create a new workbook
      const workbook = XLSX.utils.book_new();

      // Add Deals sheet
      const dealsSheet = XLSX.utils.json_to_sheet(deals.map(deal => ({
        ID: deal.id,
        Name: deal.name,
        Description: deal.description,
        Investment_Amount: deal.investment_amount,
        Entry_Date: deal.entry_date,
        Estimated_Holding_Period_Years: deal.estimated_holding_period_years,
        Status: deal.status,
        Sector: deal.sector,
        Stage: deal.stage,
        Created_Date: deal.created_date,
        Updated_Date: deal.updated_date,
        Created_By: deal.created_by,
        Enabled_For_Analysis: deal.enabled_for_analysis,
        Waterfall_LP_Pref: deal.waterfall_lp_pref,
        Waterfall_GP_Catchup: deal.waterfall_gp_catchup,
        Waterfall_Split_1_Threshold: deal.waterfall_split_1_threshold,
        Waterfall_Split_1_GP: deal.waterfall_split_1_gp,
        Waterfall_Split_2_GP: deal.waterfall_split_2_gp,
        Valuation_Snapshots: JSON.stringify(deal.valuation_snapshots)
      })));
      XLSX.utils.book_append_sheet(workbook, dealsSheet, "Deals");

      // Add Limited Partners sheet
      const lpsSheet = XLSX.utils.json_to_sheet(lps.map(lp => ({
        ID: lp.id,
        Name: lp.name,
        Email: lp.email,
        Phone: lp.phone,
        Commitment_Amount: lp.commitment_amount,
        Status: lp.status,
        Onboarding_Date: lp.onboarding_date,
        Accredited_Investor: lp.accredited_investor,
        Created_Date: lp.created_date,
        Updated_Date: lp.updated_date,
        Created_By: lp.created_by
      })));
      XLSX.utils.book_append_sheet(workbook, lpsSheet, "Limited Partners");

      // Add General Partners sheet
      const gpsSheet = XLSX.utils.json_to_sheet(gps.map(gp => ({
        ID: gp.id,
        Name: gp.name,
        Ownership_Percentage: gp.ownership_percentage,
        Email: gp.email,
        Phone: gp.phone,
        Status: gp.status,
        Created_Date: gp.created_date,
        Updated_Date: gp.updated_date,
        Created_By: gp.created_by
      })));
      XLSX.utils.book_append_sheet(workbook, gpsSheet, "General Partners");

      // Add Investments sheet
      const investmentsSheet = XLSX.utils.json_to_sheet(investments.map(inv => ({
        ID: inv.id,
        LP_ID: inv.lp_id,
        Deal_ID: inv.deal_id,
        Amount: inv.amount,
        Investment_Date: inv.investment_date,
        Allocation_Percentage: inv.allocation_percentage,
        Current_Value: inv.current_value,
        Notes: inv.notes,
        Created_Date: inv.created_date,
        Updated_Date: inv.updated_date,
        Created_By: inv.created_by
      })));
      XLSX.utils.book_append_sheet(workbook, investmentsSheet, "Investments");

      // Add Capital Activities sheet
      const activitiesSheet = XLSX.utils.json_to_sheet(capitalActivities.map(activity => ({
        ID: activity.id,
        LP_ID: activity.lp_id,
        Type: activity.type,
        Amount: activity.amount,
        Date: activity.date,
        Notes: activity.notes,
        Deal_ID: activity.deal_id,
        Is_AutoGenerated: activity.is_autogenerated_from_investment,
        Created_Date: activity.created_date,
        Updated_Date: activity.updated_date,
        Created_By: activity.created_by
      })));
      XLSX.utils.book_append_sheet(workbook, activitiesSheet, "Capital Activities");

      // Add Users sheet
      const usersSheet = XLSX.utils.json_to_sheet(users.map(user => ({
        ID: user.id,
        Full_Name: user.full_name,
        Email: user.email,
        Role: user.role,
        Created_Date: user.created_date
      })));
      XLSX.utils.book_append_sheet(workbook, usersSheet, "Users");

      // Generate Excel file and trigger download
      const fileName = `A2Z_Equity_Backup_${new Date().toISOString().split('T')[0]}.xlsx`;
      XLSX.writeFile(workbook, fileName);

      setIsExporting(false);
    } catch (error) {
      console.error("Error exporting data:", error);
      setIsExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6">
      <div className="max-w-3xl mx-auto">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-slate-800 tracking-tight">Data Backup</h1>
          <p className="text-slate-600 mt-2">Export all your fund data to Excel</p>
        </div>

        <Card className="border-slate-200 bg-white shadow-lg">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-xl">
              <Database className="w-6 h-6 text-blue-600" />
              Export Database
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-3">
              <p className="text-slate-700">
                Download a complete backup of all your fund management data including:
              </p>
              <ul className="list-disc list-inside space-y-2 text-slate-600 ml-4">
                <li>All deals and valuation snapshots</li>
                <li>Limited partners and commitments</li>
                <li>General partners</li>
                <li>Investments and allocations</li>
                <li>Capital activities (calls, distributions, receipts)</li>
                <li>Users and access information</li>
              </ul>
            </div>

            <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
              <p className="text-sm text-amber-800">
                <strong>Note:</strong> The Excel file will contain multiple sheets, one for each data type.
                All data is exported as of {new Date().toLocaleDateString()}.
              </p>
            </div>

            <Button 
              onClick={exportToExcel} 
              disabled={isExporting}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white"
              size="lg"
            >
              {isExporting ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                  Exporting...
                </>
              ) : (
                <>
                  <Download className="w-5 h-5 mr-2" />
                  Download Excel Backup
                </>
              )}
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}