
import React, { useState, useEffect, useCallback } from "react";
import { Deal } from "@/entities/Deal";
import { Investment } from "@/entities/Investment";
import { LimitedPartner } from "@/entities/LimitedPartner";
import { GeneralPartner } from "@/entities/GeneralPartner";
import { CapitalActivity } from "@/entities/CapitalActivity";
import { Button } from "@/components/ui/button";
import { Plus, Search, List, LayoutGrid } from "lucide-react";
import { AnimatePresence } from "framer-motion";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

import DealForm from "../components/deals/DealForm";
import DealCard from "../components/deals/DealCard";
import DealTable from "../components/deals/DealTable";
import DeleteConfirmationDialog from "../components/ui/DeleteConfirmationDialog";
import PortfolioProjections from "../components/deals/PortfolioProjections";
import WaterfallBreakdown from "../components/deals/WaterfallBreakdown";

export default function DealsPage() {
    const [deals, setDeals] = useState([]);
    const [lps, setLps] = useState([]);
    const [gps, setGps] = useState([]);
    const [investments, setInvestments] = useState([]);
    const [showForm, setShowForm] = useState(false);
    const [editingDeal, setEditingDeal] = useState(null);
    const [searchTerm, setSearchTerm] = useState("");
    const [statusFilter, setStatusFilter] = useState("all");
    const [viewMode, setViewMode] = useState("list"); // Changed from "grid" to "list"
    const [isLoading, setIsLoading] = useState(true);
    const [dealToDelete, setDealToDelete] = useState(null);
    const [activeTab, setActiveTab] = useState("management");
    const [selectedDealsForWaterfall, setSelectedDealsForWaterfall] = useState(new Set());
    const [sharedProjectionData, setSharedProjectionData] = useState([]);

    const loadData = useCallback(async () => {
        setIsLoading(true);
        try {
            const [dealsData, lpsData, investmentsData, gpsData] = await Promise.all([
                Deal.list('-entry_date'),
                LimitedPartner.list(),
                Investment.list(),
                GeneralPartner.list()
            ]);
            setDeals(dealsData);
            setLps(lpsData);
            setInvestments(investmentsData);
            setGps(gpsData);

            // Default all deals to be selected for waterfall analysis
            const allDealIds = new Set(dealsData.map(deal => deal.id));
            setSelectedDealsForWaterfall(allDealIds);

            // Check for deal_id in URL to pre-open edit form
            const urlParams = new URLSearchParams(window.location.search);
            const dealIdFromUrl = urlParams.get('deal_id');
            if (dealIdFromUrl) {
                const dealToEdit = dealsData.find(d => d.id === dealIdFromUrl);
                if (dealToEdit) {
                    setEditingDeal(dealToEdit);
                    setShowForm(true);
                }
            }
        } catch (error) {
            console.error("Error loading deals data:", error);
        } finally {
            setIsLoading(false);
        }
    }, []);

    useEffect(() => {
        loadData();
    }, [loadData]);

    const handleDealSubmit = async (dealData, dealInvestments) => {
        let dealId;

        if (editingDeal) {
            dealId = editingDeal.id;
            await Deal.update(dealId, dealData);

            // Find and delete auto-generated capital activities associated with this deal
            const autoGenActivities = await CapitalActivity.filter({
                deal_id: dealId,
                is_autogenerated_from_investment: true
            });
            for (const act of autoGenActivities) {
                await CapitalActivity.delete(act.id);
            }

            // Delete old investments to be replaced
            const existingInvestments = await Investment.filter({ deal_id: dealId });
            for (const inv of existingInvestments) {
                await Investment.delete(inv.id);
            }
        } else {
            const newDeal = await Deal.create(dealData);
            dealId = newDeal.id;
        }

        // Create new investments
        const newInvestments = dealInvestments.map(inv => ({
            ...inv,
            deal_id: dealId
        }));

        if (newInvestments.length > 0) {
            await Investment.bulkCreate(newInvestments);
        }

        // Create corresponding new auto-generated capital activities
        const capitalActivitiesToCreate = newInvestments.map(inv => ({
            lp_id: inv.lp_id,
            deal_id: dealId,
            type: 'contribution',
            amount: inv.amount,
            date: inv.investment_date,
            notes: `Investment in deal: ${dealData.name}`,
            is_autogenerated_from_investment: true
        }));

        if (capitalActivitiesToCreate.length > 0) {
            await CapitalActivity.bulkCreate(capitalActivitiesToCreate);
        }

        setShowForm(false);
        setEditingDeal(null);
        loadData();
    };

    const handleEdit = (deal) => {
        setEditingDeal(deal);
        setShowForm(true);
    };

    const handleDeleteDeal = async () => {
        if (!dealToDelete) return;

        try {
            // First, delete auto-generated capital activities for this deal
            const autoGenActivities = await CapitalActivity.filter({
                deal_id: dealToDelete.id,
                is_autogenerated_from_investment: true
            });
            for (const act of autoGenActivities) {
                await CapitalActivity.delete(act.id);
            }

            // Then, fetch fresh list of investments to delete to avoid using stale state
            const investmentsToDelete = await Investment.filter({ deal_id: dealToDelete.id });
            for (const inv of investmentsToDelete) {
                await Investment.delete(inv.id);
            }

            // Finally, delete the deal
            await Deal.delete(dealToDelete.id);

            setDealToDelete(null);
            loadData();
        } catch (error) {
            console.error("Error deleting deal:", error);
        }
    };

    const handleToggleDealForWaterfall = (dealId, selected) => {
        setSelectedDealsForWaterfall(prev => {
            const newSet = new Set(prev);
            if (selected) {
                newSet.add(dealId);
            } else {
                newSet.delete(dealId);
            }
            return newSet;
        });
    };

    const filteredDeals = deals.filter(deal => {
        const matchesSearch = deal.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                              (deal.sector && deal.sector.toLowerCase().includes(searchTerm.toLowerCase()));
        const matchesStatus = statusFilter === 'all' || deal.status === statusFilter;
        return matchesSearch && matchesStatus;
    });

    const getInvestmentsForDeal = useCallback((dealId) => {
        return investments.filter(inv => inv.deal_id === dealId);
    }, [investments]);

    const handleProjectionDataUpdate = (data) => {
        setSharedProjectionData(data);
    };

    const selectedDeals = deals.filter(deal => selectedDealsForWaterfall.has(deal.id));

    return (
        <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 p-6">
            <div className="max-w-7xl mx-auto space-y-8">
                <div className="flex justify-between items-center">
                    <div>
                        <h1 className="text-4xl font-bold text-slate-800 tracking-tight">Deal Management</h1>
                        <p className="text-slate-600 mt-2">Manage your portfolio deals and view projected returns</p>
                    </div>
                    <Button onClick={() => setShowForm(true)} className="bg-blue-600 hover:bg-blue-700">
                        <Plus className="w-5 h-5 mr-2" />
                        Add Deal
                    </Button>
                </div>

                <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
                    <TabsList className="grid w-full grid-cols-2">
                        <TabsTrigger value="management">Deal Management</TabsTrigger>
                        <TabsTrigger value="projections">Portfolio Projections</TabsTrigger>
                    </TabsList>

                    <TabsContent value="management" className="space-y-8">
                        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
                            <div className="flex-1 flex gap-2 w-full"> {/* Removed md:w-auto as flex-1 handles growth, kept w-full for small screens */}
                                <div className="relative flex-1"> {/* Changed w-full to flex-1 to allow search input to grow */}
                                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                                    <Input
                                        placeholder="Search deals by name or sector..."
                                        value={searchTerm}
                                        onChange={(e) => setSearchTerm(e.target.value)}
                                        className="pl-10"
                                    />
                                </div>
                                <Select value={statusFilter} onValueChange={setStatusFilter}>
                                    <SelectTrigger className="w-40 flex-shrink-0"> {/* Added flex-shrink-0 to maintain fixed width */}
                                        <SelectValue placeholder="Status" />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="all">All Statuses</SelectItem>
                                        <SelectItem value="active">Active</SelectItem>
                                        <SelectItem value="exited">Exited</SelectItem>
                                        <SelectItem value="written_off">Written Off</SelectItem>
                                        <SelectItem value="on_hold">On Hold</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                            <div className="flex items-center gap-2">
                                <Tabs value={viewMode} onValueChange={setViewMode}>
                                    <TabsList className="bg-white border">
                                        <TabsTrigger value="grid"><LayoutGrid className="w-5 h-5" /></TabsTrigger>
                                        <TabsTrigger value="list"><List className="w-5 h-5" /></TabsTrigger>
                                    </TabsList>
                                </Tabs>
                            </div>
                        </div>

                        <AnimatePresence>
                            {showForm && (
                                <DealForm
                                    deal={editingDeal}
                                    lps={lps}
                                    initialInvestments={editingDeal ? getInvestmentsForDeal(editingDeal.id) : []}
                                    onSubmit={handleDealSubmit}
                                    onCancel={() => {
                                        setShowForm(false);
                                        setEditingDeal(null);
                                    }}
                                />
                            )}
                        </AnimatePresence>

                        {isLoading ? (
                            <div className="flex justify-center items-center py-12">
                                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                            </div>
                        ) : (
                            <>
                                {filteredDeals.length === 0 && (searchTerm || statusFilter !== 'all') ? (
                                    <div className="text-center py-8 text-slate-500">No deals found matching your criteria.</div>
                                ) : filteredDeals.length === 0 ? (
                                    <div className="text-center py-8 text-slate-500">No deals added yet. Click "Add Deal" to get started!</div>
                                ) : (
                                    viewMode === "grid" ? (
                                        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                                            <AnimatePresence>
                                                {filteredDeals.map((deal) => (
                                                    <DealCard
                                                        key={deal.id}
                                                        deal={deal}
                                                        onEdit={handleEdit}
                                                        onDelete={(deal) => setDealToDelete(deal)}
                                                        selectedForWaterfall={selectedDealsForWaterfall.has(deal.id)}
                                                        onToggleWaterfall={handleToggleDealForWaterfall}
                                                    />
                                                ))}
                                            </AnimatePresence>
                                        </div>
                                    ) : (
                                        <DealTable
                                            deals={filteredDeals}
                                            onEdit={handleEdit}
                                            onDelete={(deal) => setDealToDelete(deal)}
                                            selectedDealsForWaterfall={selectedDealsForWaterfall}
                                            onToggleWaterfall={handleToggleDealForWaterfall}
                                        />
                                    )
                                )}
                            </>
                        )}

                        {/* Waterfall Analysis Section */}
                        {selectedDeals.length > 0 && (
                            <div className="mt-12 pt-8 border-t border-slate-200">
                                <WaterfallBreakdown
                                    deals={selectedDeals}
                                    investments={investments}
                                    lps={lps}
                                    gps={gps}
                                />
                            </div>
                        )}
                    </TabsContent>

                    <TabsContent value="projections" className="space-y-6">
                        <PortfolioProjections 
                            deals={deals} 
                            investments={investments} 
                            lps={lps}
                            onProjectionDataUpdate={handleProjectionDataUpdate}
                        />
                    </TabsContent>
                </Tabs>

                <DeleteConfirmationDialog
                    open={!!dealToDelete}
                    onOpenChange={() => setDealToDelete(null)}
                    onConfirm={handleDeleteDeal}
                    title={`Delete Deal: ${dealToDelete?.name || ''}`}
                    description="This will permanently delete the deal and all associated LP investments. This action cannot be undone."
                />
            </div>
        </div>
    );
}
